version: 0.2

phases:
  pre_build:
    commands:
      - echo log in to Amazon ECR...
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - aws configure list
      # - $(aws ecr get-login --no-include-email --region ap-southeast-1)
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 229671038351.dkr.ecr.ap-southeast-1.amazonaws.com/ecs-devops-hello-world
      - REPOSITORY_URI=229671038351.dkr.ecr.ap-southeast-1.amazonaws.com/ecs-devops-hello-world
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image.
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo write definitions file...
      - printf '[{"name":"ecs-devops-hello-world","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json