version: "3"
services:
  devops-nginx:
    image: nginx
    ports:
      - 8088:80
    networks:
      - devops

  devops-mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=my-secret-pw
    ports:
      - 33069:3306
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - devops

networks:
  devops:
    driver: bridge